name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go



    - name: Check out code into the Go module directory
      run: actions/checkout@v2

    - name: Test
      run: make test